empleo_proj2:
  outputs:
    dev:
      dataset: prueba_1
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt-service-account.json
      location: us-east4
      method: oauth
      priority: interactive
      project: 	dogwood-reserve-362512
      threads: 3
      type: bigquery
  target: dev
loa:
  outputs:
    dev:
      dataset: transformation_stage
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt-service-account.json      
      location: us-east4
      method: service-account
      priority: interactive
      project: dogwood-reserve-362512
      threads: 3
      type: bigquery
  target: dev