empleo_proj2:
  outputs:
    dev:
      dataset: prueba_1
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt-service-account.json
      location: us-east4
      method: oauth
      priority: interactive
      project: 	cobalt-particle-361019
      threads: 3
      type: bigquery
  target: dev
loa:
  outputs:
    dev:
      dataset: data_us
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /secrets/dbt-service-account.json
      location: us
      method: service-account
      priority: interactive
      project: cobalt-particle-361019
      threads: 3
      type: bigquery
  target: dev